schema_version = "1.0.0"
id = "Material_slot_visibility"
version = "1.0.0"
name = "Material Slot Visibility"
tagline = "viewport/render visibility"
maintainer = "MeD"
type = "add-on"
website = "https://github.com/MeD-Blender/Material-Slot-Visibility" 
tags = ["Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 MeD"]
